(require 'key-chord)
(require 'evil)
(require 'evil-leader)
(require 'mode-line-color)
(require 'evil-mode-line)
;; (require 'evil-textobj-between)
(require 'surround)

(setq key-chord-two-keys-delay 0.2)
(global-evil-leader-mode)
(evil-leader/set-leader ",")

(define-key evil-insert-state-map "\C-e" 'end-of-line)
(key-chord-define global-map ",," 'evil-buffer)

;; main file, buffer nav bindings
;; (evil-leader/set-key "t" 'projectile-find-file)
(evil-leader/set-key "t" 'fiplr-find-file)
(evil-leader/set-key "b" 'ido-switch-buffer)
(evil-leader/set-key "r" 'prelude-recentf-ido-find-file)

;; (key-chord-define global-map "\\t" 'projectile-find-file)
(key-chord-define global-map "\\t" 'fiplr-find-file)
(key-chord-define global-map "\\b" 'ido-switch-buffer)
(key-chord-define global-map "\\r" 'prelude-recentf-ido-find-file)
(key-chord-define global-map "\\G" 'magit-status)

;; (key-chord-define global-map "\\m" 'ra/find-model)
;; (key-chord-define global-map "\\c" 'ra/find-controller)
;; (key-chord-define global-map "\\v" 'ra/find-view)
;; (key-chord-define global-map "\\j" 'ra/find-js)
;; (key-chord-define global-map "\\F" 'ra/find-factory)
;; (key-chord-define global-map "\\f" 'ra/find-feature)
;; (key-chord-define global-map "\\l" 'ra/find-lib)
;; (key-chord-define global-map "\\s" 'ra/find-style)
;; (key-chord-define global-map "\\g" 'ra/find-gemfile)
;; (key-chord-define global-map "\\s" 'ra/find-schema-file)
;; (key-chord-define global-map "\\r" 'ra/find-routes-file)


(define-key prelude-mode-map (kbd "C-c r") 'prelude-recentf-ido-find-file)
(define-key prelude-mode-map (kbd "C-c R") 'prelude-rename-file-and-buffer)
;; (define-key prelude-mode-map (kbd "C-c t") 'projectile-find-file)
(define-key prelude-mode-map (kbd "C-c t") 'fiplr-find-file)
(define-key prelude-mode-map (kbd "C-c T") 'eshell-other-window)
(define-key global-map (kbd "C-c b") 'ido-switch-buffer)

(define-key evil-normal-state-map (kbd "<tab>") 'indent-for-tab-command)
(define-key evil-normal-state-map (kbd "C-<tab>") 'hs-toggle-hiding)
(define-key evil-normal-state-map "\C-e" 'end-of-line)
(define-key evil-insert-state-map "\C-f" 'evil-forward-char)
(define-key evil-insert-state-map "\C-b" 'evil-backward-char)
(define-key evil-insert-state-map "\C-d" 'evil-delete-char)
(define-key evil-insert-state-map "\C-n" 'evil-next-line)
(define-key evil-insert-state-map "\C-p" 'evil-previous-line)
(define-key evil-insert-state-map "\C-w" 'evil-delete)
(define-key evil-insert-state-map "\C-y" 'yank)
(define-key evil-insert-state-map "\C-k" 'kill-line)
;; (define-key evil-normal-state-map (kbd "SPC") 'ace-jump-word-mode)
;; (define-key evil-normal-state-map (kbd "C-SPC") 'ace-jump-line-mode)

(define-key evil-motion-state-map (kbd "C-;") 'evil-repeat-find-char-reverse)

(key-chord-define evil-insert-state-map "jk" 'evil-normal-state)
;; (key-chord-define evil-normal-state-map "ss" 'save-buffer)
(key-chord-define evil-normal-state-map "ww" 'save-buffer)
(key-chord-define evil-normal-state-map "]q" 'next-error)
(key-chord-define evil-normal-state-map "[q" 'previous-error)
;; The use of 'c' here fucks everything up with evil, understandably
;; (key-chord-define evil-normal-state-map "]c" 'git-gutter:next-hunk)
;; (key-chord-define evil-normal-state-map "[c" 'git-gutter:previous-hunk)
(key-chord-define evil-normal-state-map "]f" 'ra/find-next-file)
(key-chord-define evil-normal-state-map "[f" 'ra/find-prev-file)
(evil-leader/set-key "gm" 'ra/find-model)
(evil-leader/set-key "gc" 'ra/find-controller)
(evil-leader/set-key "gv" 'ra/find-view)
(evil-leader/set-key "gj" 'ra/find-js)
(evil-leader/set-key "gt" 'ra/find-test)
(evil-leader/set-key "gF" 'ra/find-factory)
(evil-leader/set-key "gf" 'ra/find-feature)
(evil-leader/set-key "gl" 'ra/find-lib)
(evil-leader/set-key "gs" 'ra/find-style)
(evil-leader/set-key "gG" 'ra/find-gemfile)
(evil-leader/set-key "gS" 'ra/find-schema-file)
(evil-leader/set-key "gR" 'ra/find-routes-file)
(evil-leader/set-key "G" 'magit-status)

(key-chord-mode 1)

(evil-leader/set-key "ga" 'ra/find-alternate-file-other-window)

(evil-leader/set-key "wh" 'evil-window-left)
(evil-leader/set-key "wl" 'evil-window-right)
(evil-leader/set-key "wj" 'evil-window-down)
(evil-leader/set-key "wk" 'evil-window-up)
(evil-leader/set-key "ws" 'evil-window-split)
(evil-leader/set-key "wv" 'evil-window-vsplit)

(key-chord-define evil-normal-state-map "HH" 'evil-window-left)
(key-chord-define evil-normal-state-map "LL" 'evil-window-right)
(key-chord-define evil-normal-state-map "KK" 'evil-window-up)
(key-chord-define evil-normal-state-map "JJ" 'evil-window-down)
(key-chord-define evil-normal-state-map "PP" 'evil-window-mru)

(define-key evil-insert-state-map (kbd "C-c C-k") 'yas-expand)

(define-key prelude-mode-map (kbd "C-c o") nil)


(global-set-key (kbd "C-c o") 'occur)

(global-set-key (kbd "C-,") 'er/expand-region)
(global-set-key (kbd "C-<") 'mc/mark-next-like-this)
(define-key global-map (kbd "A-/") 'hippie-expand)
(define-key global-map (kbd "C-c C-j") 'dired-jump)
(global-set-key (kbd "C-c C-r") 'mc/mark-sgml-tag-pair)

(key-chord-define evil-normal-state-map "DD" 'prelude-duplicate-current-line-or-region)
