(require 'key-chord)
(require 'evil)
(require 'evil-leader)
(require 'mode-line-color)
(require 'evil-mode-line)
(require 'evil-textobj-between)
(require 'surround)

(setq key-chord-two-keys-delay 0.2)
(evil-leader/set-leader ",")

(define-key evil-insert-state-map "\C-e" 'end-of-line)
(key-chord-define global-map ",t" 'projectile-find-file)
(key-chord-define global-map ",b" 'ido-switch-buffer)
(key-chord-define global-map ",r" 'prelude-recentf-ido-find-file)
(key-chord-define global-map ",," 'evil-buffer)

(define-key evil-normal-state-map (kbd "<tab>") 'indent-for-tab-command)
(define-key evil-normal-state-map (kbd "C-<tab>") 'hs-toggle-hiding)
(define-key evil-normal-state-map "\C-e" 'end-of-line)
(define-key evil-insert-state-map "\C-f" 'evil-forward-char)
(define-key evil-insert-state-map "\C-b" 'evil-backward-char)
(define-key evil-insert-state-map "\C-d" 'evil-delete-char)
(define-key evil-insert-state-map "\C-n" 'evil-next-line)
(define-key evil-insert-state-map "\C-p" 'evil-previous-line)
(define-key evil-insert-state-map "\C-w" 'evil-delete)
(define-key evil-insert-state-map "\C-y" 'yank)
(define-key evil-insert-state-map "\C-k" 'kill-line)
(define-key evil-normal-state-map (kbd "SPC") 'ace-jump-word-mode)
(define-key evil-normal-state-map (kbd "C-SPC") 'ace-jump-line-mode)

(define-key evil-motion-state-map (kbd "C-;") 'evil-repeat-find-char-reverse)

(key-chord-define evil-insert-state-map "jk" 'evil-normal-state)
;; (key-chord-define evil-normal-state-map "ss" 'save-buffer)
(key-chord-define evil-normal-state-map "ss" 'save-buffer)
(key-chord-define evil-normal-state-map "ww" 'save-buffer)
;; (key-chord-define evil-normal-state-map "oo" nil)
;; (key-chord-define evil-normal-state-map "bb" nil)
(key-chord-define evil-normal-state-map "]q" 'next-error)
(key-chord-define evil-normal-state-map "[q" 'previous-error)
(key-chord-define evil-normal-state-map "]c" 'git-gutter:next-hunk)
(key-chord-define evil-normal-state-map "[c" 'git-gutter:previous-hunk)
(key-chord-define evil-normal-state-map "]f" 'pr/find-next-file)
(key-chord-define evil-normal-state-map "[f" 'pr/find-prev-file)
;; (key-chord-define evil-normal-state-map ";;" 'er/expand-region)
(key-chord-mode 1)

(evil-leader/set-key "gs" 'magit-status)
(evil-leader/set-key "gm" 'current-project-find-rails-model)
(evil-leader/set-key "gc" 'current-project-find-rails-controller)
(evil-leader/set-key "gv" 'current-project-find-rails-view)
(evil-leader/set-key "gj" 'current-project-find-rails-javascript)
(evil-leader/set-key "gt" 'current-project-find-rails-test)
(evil-leader/set-key "gG" 'current-project-find-rails-gemfile)
(evil-leader/set-key "gS" 'current-project-find-rails-db-schema)
(evil-leader/set-key "gR" 'current-project-find-rails-routes)
(evil-leader/set-key "ga" 'pr/find-alternate-file-other-window)

(evil-leader/set-key "wh" 'evil-window-left)
(evil-leader/set-key "wl" 'evil-window-right)
(evil-leader/set-key "wj" 'evil-window-down)
(evil-leader/set-key "wk" 'evil-window-up)
(evil-leader/set-key "ws" 'evil-window-split)
(evil-leader/set-key "wv" 'evil-window-vsplit)
(key-chord-define-global "JJ" 'evil-window-next)
(key-chord-define-global "KK" 'evil-window-prev)
(key-chord-define-global "LL" 'evil-window-mru)
;; (evil-leader/set-key "e" 'er/expand-region)
;; (evil-leader/set-key "t" 'projectile-find-file)
;; (evil-leader/set-key "b" 'ido-switch-buffer)
;; (evil-leader/set-key "r" 'prelude-recentf-ido-find-file)

(define-key evil-insert-state-map (kbd "C-c C-k") 'yas-expand)

;; ;;; esc quits
;; (define-key evil-normal-state-map [escape] 'keyboard-quit)
;; (define-key evil-visual-state-map [escape] 'keyboard-quit)
;; (define-key minibuffer-local-map [escape] 'minibuffer-keyboard-quit)
;; (define-key minibuffer-local-ns-map [escape] 'minibuffer-keyboard-quit)
;; (define-key minibuffer-local-completion-map [escape] 'minibuffer-keyboard-quit)
;; (define-key minibuffer-local-must-match-map [escape] 'minibuffer-keyboard-quit)
;; (define-key minibuffer-local-isearch-map [escape] 'minibuffer-keyboard-quit)


(define-key prelude-mode-map (kbd "C-c o") nil)
(global-set-key (kbd "C-c o") 'occur)

(global-set-key (kbd "C-,") 'er/expand-region)
(global-set-key (kbd "C-<") 'mc/mark-next-like-this)
(define-key global-map (kbd "A-/") 'hippie-expand)
(define-key global-map (kbd "C-c C-j") 'dired-jump)
(global-set-key (kbd "C-c C-r") 'mc/mark-sgml-tag-pair)
